import { FusesPlugin } from '@electron-forge/plugin-fuses'
import { FuseV1Options, FuseVersion } from '@electron/fuses'

module.exports = {
	packagerConfig: {
		asar: true,
		// Ensure native modules are unpacked to avoid issues at runtime
		extraResource: ['./db/schema.sqlite', './db/seed.sqlite'],
	},
	// Add force rebuild to ensure C++ compilation targets the specific Electron version
	rebuildConfig: {
		force: true,
		onlyModules: ['better-sqlite3'],
	},
	makers: [
		// Windows (Squirrel) - generated by Windows jobs
		{
			name: '@electron-forge/maker-squirrel',
			config: {
				authors: 'Armageddion',
				description: 'Adrenalin CRM application',
			},
		},
		// macOS (Zip) - generated by macOS jobs
		// Note: Without code signing, these apps will warn users they are damaged/untrusted
		{
			name: '@electron-forge/maker-zip',
			platforms: ['darwin'],
			config: {
				options: {
					maintainer: 'Armageddion',
					homepage: 'https://github.com/armageddion/adrenalin',
				},
			},
		},
		// Linux (Zip) - simple archive for Linux
		{
			name: '@electron-forge/maker-zip',
			platforms: ['linux'],
			config: {
				options: {
					maintainer: 'Armageddion',
					homepage: 'https://github.com/armageddion/adrenalin',
				},
			},
		},
		// Linux (AppImage) - works on any Linux distribution
		{
			name: '@reforged/maker-appimage',
			platforms: ['linux'],
			config: {
				options: {
					maintainer: 'Armageddion',
					homepage: 'https://github.com/armageddion/adrenalin',
					icon: 'src/assets/logo.svg',
					categories: ['Office'],
				},
			},
		},
	],
	plugins: [
		{
			name: '@electron-forge/plugin-auto-unpack-natives',
			config: {},
		},
		new FusesPlugin({
			version: FuseVersion.V1,
			[FuseV1Options.RunAsNode]: false,
			[FuseV1Options.EnableCookieEncryption]: true,
			[FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
			[FuseV1Options.EnableNodeCliInspectArguments]: false,
			[FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
			[FuseV1Options.OnlyLoadAppFromAsar]: true,
		}),
	],
	publishers: [
		{
			name: '@electron-forge/publisher-github',
			config: {
				repository: {
					owner: 'armageddion',
					name: 'adrenalin',
				},
				prerelease: false,
				draft: false,
			},
		},
	],
}
